### ISSUE TITLE
Login/CreateUser

### ISSUE THREAD

**Issue by CyberHummel** [CyberHummel/Rate-ME#1]

**Comment by CyberHummel** [comment]
Problem war das man sich nur vom Server aus mit der DB-Verbinden kann, Problem ist (gelöst), da jeder sich zu DEV-Swecken selber eine DB machen muss mit XAMPP (selbes Problem wurde auch schon im anderen issue besprochen)

**Comment by Unofficialret3** [comment]
siehe issue login page
